import { AppRoutes } from '@/lib/utils/constants/AppRoutes';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Providers from '@/lib/utils/Providers/Provider.client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Players App with Next.js and Prisma',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen font-medium`}
      >
        <header className="flex justify-between items-center p-4 bg-white shadow">
          <Link href={AppRoutes.Home}>
            <h1 className="text-2xl font-bold">Players</h1>
          </Link>
        </header>

        <main className="flex flex-col items-center p-4 overflow-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
